### ISSUE TITLE
Doesn't work with sbt-native-packager

### ISSUE THREAD

**Issue by anthonylau** [sbt/sbt-aspectj#26]
Not sure if I should post here or `sbt-native-packager`.

When I package with `sbt docker:publishLocal` with `enablePlugins(JavaAppPackaging)`, it doesn't add the agent option to `bashScriptExtraDefines`.

Then I found this but it's no longer available on bintray repository. 
https://github.com/gilt/sbt-aspectjweaver

Would anyone advice?

**Comment by alonsodomin** [comment]
I don't believe that adding a dependency to `sbt-native-packager` (or the other way around) would be a good idea. But you could combine both plugins using this other one:
https://github.com/sbt/sbt-javaagent

Then, having the AspectJ Weaver being used at startup could be done with:
```
javaAgents += (aspectjWeaver in Aspectj).value
```

I'm going to close this for now.

**Comment by jalaziz** [comment]
@alonsodomin This is not possible with the current version of `sbt-aspectj` and `sbt-javaagent`. The main issue is that `javaAgents` expect an `AgentModule` (which requires a `ModuleID`) and `aspectjWeaver in Aspectj` returns a `File`.

This could probably resolved by abstracting out the module in `sbt-aspectj` as a separate option. It's also possible to resolve this with changes to `sbt-javaagent` but it would require more refactoring to support direct references to a `File` at first glance.
