### ISSUE TITLE
sbt-aspectj not found

### ISSUE THREAD

**Issue by cubean** [sbt/sbt-aspectj#38]
Now, there is no available version 

addSbtPlugin("com.lightbend.sbt" % "sbt-aspectj" % "{version}")

Error:Unresolved dependencies:<ul><li> com.lightbend.sbt#sbt-aspectj;0.13.15: not found</li></ul>See complete log in <a href="file:/Users/cubeanliu/Library/Logs/IntelliJIdea2017.2/sbt.last.log">file:/Users/cubeanliu/Library/Logs/IntelliJIdea2017.2/sbt.last.log</a>

 I tried version 0.13.13, 0.13.15, 1.0.0, 1.0.2, they are all not working.

What's the problem now?

**Comment by bantonsson** [comment]
Hi @cubean,

If you look under [releases](https://github.com/sbt/sbt-aspectj/releases), you will see that the version for sbt-aspectj is 0.11.0

Yes, the README is a bit confusing, I will update it to include a version number link to the latest released version.
